Repository Techeer-H/frontend, pull requests merged in 2024-02, with the labels that each got.

#145 143_Design/온보딩 두번째 4번째페이지 제작
  forten/package.json
  forten/src/pages/login/main/styles.tsx
  forten/src/pages/onboard/jaeminSecond/index.tsx
  forten/src/pages/onboard/jaeminStartPage/index.tsx
  forten/src/pages/onboard/startpage/index.tsx
  forten/src/pages/onboard/startpage/styles.css
  forten/src/router.tsx
  forten/yarn.lock
Labels: Design

#150 140_design: 전체 디자인 수정
  forten/src/App.css
  forten/src/App.tsx
  forten/src/assets/testImg.png
  forten/src/assets/testImg2.png
  forten/src/components/blend/blendEnterGrades.tsx
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/wordBox.tsx
  forten/src/components/modal/writeButton.tsx
  forten/src/components/teacher/Tgraybox.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/components/teacher/TstudentInfo.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/main/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
Labels: Design

#152 151 design/모달창 v3 변경
  forten/src/pages/login/modal/ConsultantSuccessModal.tsx
  forten/src/pages/login/modal/TeacherSuccess.tsx
  forten/src/pages/login/modal/failLoginModal.tsx
Labels: Design

#153 design:스크롤 맨위로 보내기 버튼, 온보딩 구현 완료
  forten/src/assets/2ndno1.svg
  forten/src/assets/2ndno2.svg
  forten/src/assets/2ndno3.svg
  forten/src/assets/2ndno4.svg
  forten/src/assets/no1.svg
  forten/src/pages/onboard/cubepage/index.tsx
  forten/src/pages/onboard/cubepage/styles.css
  forten/src/pages/onboard/firstpage/index.tsx
  forten/src/pages/onboard/firstpage/styles.tsx
  forten/src/pages/onboard/magicpage/index.html
  forten/src/pages/onboard/magicpage/index.tsx
  forten/src/pages/onboard/magicpage/script.js
  forten/src/pages/onboard/magicpage/styles.tsx
  forten/src/pages/onboard/secondpage/index.tsx
  forten/src/pages/onboard/secondpage/styles.tsx
  forten/src/pages/onboard/thirdpage/index.tsx
  forten/src/pages/onboard/totalpage/index.tsx
  forten/src/pages/onboard/totalpage/styles.tsx
  forten/src/pages/onboard/wavepage/index.tsx
  forten/src/pages/onboard/wavepage/styles.css
  forten/src/router.tsx
Labels: Design, Feature

#156 156_Design/ 부트캠프 마지막 디자인 수정
  forten/src/assets/Ai.png
  forten/src/assets/Pdf.png
  forten/src/assets/rating.png
  forten/src/assets/test.png
  forten/src/pages/onboard/StartPage/index.tsx
  forten/src/pages/onboard/cubepage/styles.css
  forten/src/pages/onboard/firstpage/index.tsx
  forten/src/pages/onboard/firstpage/styles.tsx
  forten/src/pages/onboard/magicpage/index.html
  forten/src/pages/onboard/magicpage/index.tsx
  forten/src/pages/onboard/magicpage/script.js
  forten/src/pages/onboard/magicpage/styles.tsx
  forten/src/pages/onboard/totalpage/index.tsx
  forten/src/pages/onboard/totalpage/styles.tsx
  forten/src/pages/onboard/wavepage/styles.css
  forten/src/router.tsx
Labels: Design

#157 154_feat: pdf api 연결
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/src/pages/consultant/graderegister/inputTest.tsx
Labels: Design, Feature

#159 158_refactor: yarn build 오류 수정
  forten/src/components/blend/blendEnterGrades.tsx
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/teacher/TbookMarkList.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/consultant/graderegister/inputTest.tsx
  forten/src/pages/onboard/totalpage/index.tsx
  forten/src/pages/onboard/wavepage/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/main/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
Labels: Feature

#160 design: 디자인 수정 및, 리팩토링 진행
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/consultant/graderegister/inputTest.tsx
  forten/src/pages/consultant/modal/consultantrating.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/login/main/index.tsx
  forten/src/pages/newpages/Consultant/newModal/consultantrating.tsx
  forten/src/pages/newpages/Teacher/newModal/teacherrating.tsx
  forten/src/pages/signup/main/index.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/pages/teacher/main/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
Labels: Design, Refactor
