Repository Techeer-H/frontend, pull requests merged in 2024-01, with the labels that each got.

#5 feat: 초기세팅
  forten/.eslintrc.cjs
  forten/.gitignore
  forten/.prettierrc
  forten/Dockerfile
  forten/README.md
  forten/index.html
  forten/package.json
  forten/postcss.config.js
  forten/public/vite.svg
  forten/src/App.css
  forten/src/App.tsx
  forten/src/assets/react.svg
  forten/src/components/NavBar/ styles.tsx
  forten/src/components/NavBar/index.tsx
  forten/src/index.css
  forten/src/layouts/AuthCheckedLayout.tsx
  forten/src/main.tsx
  forten/src/pages/NotFoundPage.tsx
  forten/src/pages/login/index.tsx
  forten/src/pages/onboard/onboard.tsx
  forten/src/pages/onboard/start.tsx
  forten/src/pages/teacher/teacher.tsx
  forten/src/vite-env.d.ts
  forten/tailwind.config.js
  forten/tsconfig.json
  forten/tsconfig.node.json
  forten/vite.config.ts
  forten/yarn.lock
Labels: Setting, Feature

#8 7_[ feat]초기세팅 오류 수정
  forten/src/components/NavBar/ styles.tsx
  forten/src/components/NavBar/index.tsx
Labels: Error, Setting, Fix

#10 9_[feat]초기세팅 오류 수정
  forten/.gitignore
  forten/src/router.tsx
  yarn.lock
Labels: Error, Setting, Fix

#15 11_[fix]: 세팅 수정
  forten/.eslintrc.cjs
  forten/src/components/Navbar.tsx
  forten/src/layouts/AuthCheckedLayout.tsx
  yarn.lock
Labels: Error

#19 12_[design]/강사 메인페이지 퍼블리싱 및 Navbar, Memo 컴포넌트작성
  forten/.gitignore
  forten/src/assets/logo.svg
  forten/src/assets/profile.svg
  forten/src/assets/searchIcon.svg
  forten/src/components/Memo.tsx
  forten/src/components/Navbar.tsx
  forten/src/index.css
  forten/src/layouts/AuthCheckedLayout.tsx
  forten/src/pages/teacher/teacher.tsx
  forten/src/router.tsx
Labels: Design

#23 13_[design]/컨설턴트 메인 페이지 퍼블리싱 및 컴포넌트화
  .DS_Store
  forten/src/assets/AIPrompt.svg
  forten/src/assets/arrow.svg
  forten/src/assets/bookMark.svg
  forten/src/assets/inquireStudent.svg
  forten/src/assets/registerGrade.svg
  forten/src/assets/remove.svg
  forten/src/assets/star.svg
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/greenStatusButton.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/redStatusButton.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/teacher/memo.tsx
  forten/src/components/teacher/navBar.tsx
  forten/src/layouts/AuthCheckedLayout.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/onboard/index.tsx
  forten/src/pages/onboard/start.tsx
  forten/src/pages/onboard/styles.tsx
  forten/src/pages/teacher/teacher.tsx
  forten/src/router.tsx
Labels: Error, Design, Fix

#24 22_[design]/ 회원가입,로그인 모달창 퍼블리싱
  forten/package-lock.json
  forten/package.json
  forten/src/assets/Checkicon.svg
  forten/src/assets/Warningsign.svg
  forten/src/assets/Warningsignid.svg
  forten/src/components/modal/successmodal.tsx
  forten/src/components/modal/warningsign.tsx
  forten/src/components/modal/warningsignid.tsx
  forten/src/router.tsx
  forten/yarn.lock
Labels: Design

#29 17_[design] 컨설턴트 학생 등록 페이지 모달 퍼블리싱
  README.md
  forten/src/assets/Xicon.svg
  forten/src/components/modal/registermodal.tsx
  forten/src/components/modal/successmodal.tsx
  forten/src/components/modal/warningsign.tsx
  forten/src/components/modal/warningsignid.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
Labels: Design, Feature, Refactor

#33 20_[design]/로그인-페이지-퍼블리싱
  forten/.gitignore
  forten/src/pages/login/index.tsx
  forten/src/pages/login/styles.tsx
Labels: Design

#32 21_[design]/회원가입 페이지 퍼블리싱
  forten/src/assets/LoginImg.svg
  forten/src/assets/LoginImg2.svg
  forten/src/assets/siginuplogo.svg
  forten/src/pages/signup/index.tsx
  forten/src/pages/signup/styles.tsx
  forten/src/router.tsx
Labels: Design

#30 27_[design]/학생,학부모 만족도 모달창 퍼블리싱
  .DS_Store
  forten/src/assets/Checkicon_gradient.svg
  forten/src/assets/LogoAndLetter.svg
  forten/src/assets/close.svg
  forten/src/components/modal/consultantrating.tsx
  forten/src/components/modal/rating.tsx
  forten/src/components/modal/successmodal.tsx
  forten/src/components/modal/teacherrating.tsx
  forten/src/router.tsx
Labels: Design

#36 25_design/학생평가-페이지-퍼블리싱
  forten/src/assets/Evaluationbutton.svg
  forten/src/assets/Rectangle.svg
Labels: Design

#40 35_design: 3번째 온보딩페이지 퍼블리싱
  .DS_Store
  forten/src/pages/onboard/firstpage/index.tsx
  forten/src/pages/onboard/firstpage/styles.tsx
  forten/src/pages/onboard/thirdpage/index.tsx
  forten/src/pages/onboard/thirdpage/styles.tsx
  forten/src/router.tsx
Labels: Design

#41 design: 강사의 학생평가 페이지 퍼블리싱, memo컴포넌트 수정
  forten/package-lock.json
  forten/package.json
  forten/src/animation/submitButton.json
  forten/src/assets/evaluateImg.svg
  forten/src/components/consultant/memo.tsx
  forten/src/components/teacher/Tmemo.tsx
  forten/src/components/teacher/TsubmitButton.tsx
  forten/src/pages/signup/main/styles.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
  forten/src/router.tsx
  forten/yarn.lock
Labels: Design, Fix

#44 design: 프롬트 제작 페이지 퍼블리싱, rating 코드 수정, Navbar margin 수정
  .DS_Store
  forten/src/assets/PersonIcon.svg
  forten/src/components/consultant/navBar.tsx
  forten/src/components/modal/rating.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/schoolMock.tsx
  forten/src/components/modal/studentTable.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/pages/consultant/AiPrompt/index.tsx
  forten/src/pages/consultant/AiPrompt/styles.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/pages/teacher/modal/studentDetail.tsx
  forten/src/router.tsx
Labels: Design

#48 design: 강사 학생 평가페이지 퍼블리싱 수정
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
Labels: Design

#51 49_feat: 성적 등록 페이지 라우팅
  forten/src/components/consultant/chooseSchoolMock.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/pages/consultant/graderegister/mockTest.tsx
  forten/src/pages/consultant/graderegister/schoolTest.tsx
  forten/src/router.tsx
Labels: Feature

#52 47_[feat]/로그인 및 회원가입 기능,상태관리 구현
  forten/.eslintrc.cjs
  forten/src/pages/login/index.tsx
  forten/src/pages/login/main/index.tsx
  forten/src/pages/login/main/styles.tsx
  forten/src/pages/login/modal/failLoginModal.tsx
  forten/src/pages/login/modal/successLoginModal.tsx
  forten/src/pages/login/styles.tsx
  forten/src/pages/signup/index.tsx
  forten/src/pages/signup/main/index.tsx
  forten/src/pages/signup/main/styles.tsx
  forten/src/pages/signup/modal/successSignUpModal.tsx
  forten/src/pages/signup/styles.tsx
  forten/src/router.tsx
  forten/src/types/sutudent.ts
Labels: Design, Feature

#56 55_[feat]/성적등록 페이지 상태구현, api 연동
  forten/package-lock.json
  forten/package.json
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/consultant/gradeSelect.tsx
  forten/src/pages/consultant/graderegister/mockTest.tsx
  forten/src/pages/consultant/graderegister/schoolTest.tsx
  forten/yarn.lock
Labels: Feature

#60 feat: 컨설턴트 메인페이지 기능구현 및 api연동
  forten/.eslintrc.cjs
  forten/package.json
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/greenStatusButton.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/redStatusButton.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/yarn.lock
Labels: Design, Feature

#61 feat: ai 요약페이지 api 연결
  forten/src/assets/sadEmoji.png
  forten/src/assets/smileEmoji.png
  forten/src/components/modal/parentAvergy.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/schoolMock.tsx
  forten/src/components/modal/studentAvergy.tsx
  forten/src/components/modal/studentTable.tsx
  forten/src/components/modal/wordBox.tsx
  forten/src/components/modal/writeButton.tsx
  forten/src/pages/consultant/AiPrompt/index.tsx
  forten/src/pages/consultant/modal/consultantrating.tsx
  forten/yarn.lock
Labels: Feature

#62 57_feat/ 강사의 학생평가 등록, 평가 조회는 수정 중
  forten/src/assets/delete.svg
  forten/src/assets/modify.svg
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/modal/rating.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/consultant/modal/consultantrating.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
Labels: Feature

#64 error: 머지 후 생긴 오류 해결
  forten/src/pages/consultant/modal/consultantrating.tsx
Labels: Error

#66 error:build 에러 수정
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/components/consultant/chooseSchoolMock.tsx
  forten/src/components/consultant/gradeSelect.tsx
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/greenStatusButton.tsx
  forten/src/components/consultant/memo.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/redStatusButton.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/modal/parentAvergy.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/schoolMock.tsx
  forten/src/components/modal/studentAvergy.tsx
  forten/src/components/modal/wordBox.tsx
  forten/src/components/modal/writeButton.tsx
  forten/src/components/teacher/TbookMarkList.tsx
  forten/src/components/teacher/Tgraybox.tsx
  forten/src/components/teacher/Tmemo.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/components/teacher/TstudentInfo.tsx
  forten/src/components/teacher/TsubmitButton.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/NotFoundPage.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/consultant/graderegister/mockTest.tsx
  forten/src/pages/consultant/graderegister/schoolTest.tsx
  forten/src/pages/consultant/modal/consultantrating.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/login/main/index.tsx
  forten/src/pages/login/main/styles.tsx
  forten/src/pages/login/modal/failLoginModal.tsx
  forten/src/pages/login/modal/successLoginModal.tsx
  forten/src/pages/onboard/firstpage/index.tsx
  forten/src/pages/signup/main/index.tsx
  forten/src/pages/signup/main/styles.tsx
  forten/src/pages/signup/modal/successSignUpModal.tsx
  forten/src/pages/signup/modal/warningsign.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/index.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
  forten/src/router.tsx
Labels: Error

#68 67_featuere/로그인-회원가입-api 연동 및 학생정보조회 api 연동
  forten/src/components/consultant/studentInfo.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/login/main/index.tsx
  forten/src/pages/signup/main/index.tsx
  forten/src/pages/signup/modal/successSignUpModal.tsx
  forten/yarn.lock
Labels: Error, Design, Feature

#72 feat: 컨설턴트 메인에서 다른 페이지로 학생 id넘기기
  forten/src/components/consultant/chooseSchoolMock.tsx
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/pages/consultant/AiPrompt/index.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/graderegister/mockTest.tsx
  forten/src/pages/consultant/graderegister/schoolTest.tsx
Labels: Feature

#75 67_feat/ 로그인 회원가입 api 연동 및 기능구현 완료 그리고 로컬스토리지 및 모달창 오류수정 ,NavBar 로그아웃 구현
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/login/main/index.tsx
  forten/src/pages/login/modal/ConsultantSuccessModal.tsx
  forten/src/pages/login/modal/TeacherSuccess.tsx
  forten/src/pages/signup/main/index.tsx
Labels: Error, Design, Feature, Fix

#79 78_feat/studentinfo 디자인 전반적으로 수정, 회원가입 오류수정 ,studentinfo api연동
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/greenStatusButton.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/redStatusButton.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/signup/main/index.tsx
Labels: Error, Design, Feature, Fix

#80 70_feat/학생 평가 목록 조회 수정 삭제(CRUD)
  forten/src/components/modal/rating.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/consultant/modal/consultantrating.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
Labels: Feature

#77 73_feat: 컨설턴트 페이지들 학생 id api 연결
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/modal/parentAvergy.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/schoolMock.tsx
  forten/src/components/modal/studentAvergy.tsx
  forten/src/components/modal/studentTable.tsx
  forten/src/components/modal/wordBox.tsx
  forten/src/pages/consultant/AiPrompt/index.tsx
Labels: Feature

#82 [Feature} 컨설턴트 메인페이지 메모 새로고침 자동저장기능
  forten/src/components/consultant/memo.tsx
Labels: Feature

#84 74_feat: 컨설턴트가 학생과 학부모의 점수를 평가할 수 있습니다
  forten/src/components/modal/studentAvergy.tsx
  forten/src/components/modal/wordBox.tsx
  forten/src/pages/consultant/AiPrompt/index.tsx
  forten/src/pages/consultant/modal/consultantrating.tsx
  forten/src/pages/signup/main/styles.tsx
Labels: Error, Feature

#86 85_error: build 에러 해결
  forten/src/components/consultant/chooseSchoolMock.tsx
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/memo.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/modal/parentAvergy.tsx
  forten/src/components/modal/rating.tsx
  forten/src/components/modal/studentAvergy.tsx
  forten/src/components/modal/wordBox.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/modal/consultantrating.tsx
  forten/src/pages/login/modal/ConsultantSuccessModal.tsx
  forten/src/pages/login/modal/TeacherSuccess.tsx
  forten/src/pages/signup/main/index.tsx
  forten/src/pages/signup/modal/successSignUpModal.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/modal/studentDetail.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
  forten/src/router.tsx
Labels: Error

#88 87_feat: 파이차트 이름 불러오기 및 에러 수정
  forten/src/components/modal/parentAvergy.tsx
  forten/src/components/modal/rating.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/studentAvergy.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/modal/consultantrating.tsx
Labels: Error, Feature

#89 81_feat/즐겨찾기 기능 구현
  forten/src/assets/Mark.svg
  forten/src/assets/NoMark.svg
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/login/main/index.tsx
Labels: Design, Feature, Fix

#90 [Revert 89] 81_feature/즐겨찾기 기능구현
  forten/src/assets/Mark.svg
  forten/src/assets/NoMark.svg
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/login/main/index.tsx
Labels: Error, Feature

#92 91_Design/즐겨찾기 [로컬스토리지] 로 기능구현
  forten/src/assets/Mark.svg
  forten/src/assets/NoMark.svg
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
Labels: Error, Design, Feature, Fix

#96 94_Feat/강사페이지 전반적인 교체, 기능구현 ,컴포넌트 수정,api연동
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/teacher/TbookMarkList.tsx
  forten/src/components/teacher/Tgraybox.tsx
  forten/src/components/teacher/Tmemo.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/components/teacher/TstudentInfo.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/index.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/pages/teacher/main/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
  forten/src/pages/teacher/styles.tsx
  forten/src/router.tsx
Labels: Error, Design, Feature, Fix

#99 98_Error/yarn build 오류수정
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/teacher/TstudentInfo.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/router.tsx
Labels: Error

#106 95_Design/수정된 강사 학생 페이지
  forten/package.json
  forten/src/assets/Boxpencil.svg
  forten/src/assets/MinusLogo.svg
  forten/src/assets/NewLogo.svg
  forten/src/assets/Snow.svg
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/pagesNew/teacher/index.tsx
  forten/src/pagesNew/teacher/modal/newteacherrating.tsx
  forten/src/pagesNew/teacher/styles.tsx
  forten/src/router.tsx
  forten/vite.config.ts
  forten/yarn.lock
Labels: Design, Feature

#105 102 design 상담 후 만족도 조사 학생 평가 모달창 디자인 수정
  forten/src/assets/bg.jpg
  forten/src/assets/checkIconPurple.svg
  forten/src/assets/checkIconWhite.svg
  forten/src/assets/closeWhite.svg
  forten/src/assets/moon (2).png
  forten/src/assets/mountains_behind.png
  forten/src/assets/mountains_front.png
  forten/src/assets/stars.png
  forten/src/pages/newpages/Consultant/newModal/consultantrating.tsx
  forten/src/pages/newpages/Teacher/newModal/teacherrating.tsx
  forten/src/pages/onboard/secondpage/index.tsx
  forten/src/pages/onboard/secondpage/styles.tsx
  forten/src/pages/onboard/thirdpage/index.tsx
  forten/src/pages/onboard/thirdpage/styles.tsx
Labels: Design

#108 Revert "95_Design/수정된 강사 학생 페이지"
  forten/package.json
  forten/src/assets/Boxpencil.svg
  forten/src/assets/MinusLogo.svg
  forten/src/assets/NewLogo.svg
  forten/src/assets/Snow.svg
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/pagesNew/teacher/index.tsx
  forten/src/pagesNew/teacher/modal/newteacherrating.tsx
  forten/src/pagesNew/teacher/styles.tsx
  forten/src/router.tsx
  forten/vite.config.ts
  forten/yarn.lock
Labels: HELP!

#104 93_design: 컨설턴트 페이지 퍼블리싱 수정
  forten/package.json
  forten/src/assets/filterIcon.png
  forten/src/assets/searchIcon.png
  forten/src/assets/send.png
  forten/src/assets/signOut.png
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/memo.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/modal/parentAvergy.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/schoolMock.tsx
  forten/src/components/modal/studentAvergy.tsx
  forten/src/components/modal/wordBox.tsx
  forten/src/components/modal/writeButton.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pagesNew/consultant/aiPrompt.tsx
  forten/src/pagesNew/consultant/main.tsx
  forten/src/pagesNew/consultant/schoolTestGrades.tsx
  forten/src/router.tsx
  forten/yarn.lock
Labels: Design

#110 design: 평가 모달 디자인 수정
  forten/src/components/modal/rating.tsx
Labels: Design

#111 [Design} 1차 완성한 강사 학생 평가 페이지 퍼블리싱
  forten/src/assets/Account.svg
  forten/src/assets/Boxpencil.svg
  forten/src/assets/Logout.svg
  forten/src/assets/MinusLogo.svg
  forten/src/assets/NewLogo.svg
  forten/src/assets/Snow.svg
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pagesNew/teacher/index.tsx
  forten/src/pagesNew/teacher/styles.tsx
  forten/src/router.tsx
Labels: Design, Feature

#114 Design: V2 모든 페이지 중 70% 디자인 변경 퍼블리싱 및 기능 구현
  forten/src/assets/BlendLogo.png
  forten/src/assets/BlendLogoWhite.png
  forten/src/assets/searchIcon.svg
  forten/src/components/consultant/bookMarkList.tsx
  forten/src/components/consultant/chooseSchoolMock.tsx
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/greenStatusButton.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/redStatusButton.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/schoolMock.tsx
  forten/src/components/modal/studentAvergy.tsx
  forten/src/components/modal/studentTable.tsx
  forten/src/components/modal/writeButton.tsx
  forten/src/components/teacher/TbookMarkList.tsx
  forten/src/components/teacher/Tgraybox.tsx
  forten/src/components/teacher/Tmemo.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/components/teacher/TstudentInfo.tsx
  forten/src/pages/consultant/AiPrompt/index.tsx
  forten/src/pages/consultant/AiPrompt/styles.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/login/main/index.tsx
  forten/src/pages/login/main/styles.tsx
  forten/src/pages/signup/main/index.tsx
  forten/src/pages/signup/main/styles.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/pages/teacher/main/styles.tsx
  forten/src/pagesNew/consultant/aiPrompt.tsx
  forten/src/pagesNew/consultant/main.tsx
  forten/src/router.tsx
Labels: Design, Feature, Fix

#115 112_feature/컨설턴트 성적 등록 수정
  forten/src/components/blend/blendEnterGrades.tsx
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/pagesNew/consultant/aiPrompt.tsx
  forten/src/pagesNew/consultant/schoolTestGrades.tsx
Labels: Design, Feature

#119 116_Desgin/강사페이지 라인 퍼블리싱 완료
  forten/src/assets/For-TEN.png
  forten/src/assets/For-TEN_black.png
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/teacher/TstudentInfo.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/login/main/index.tsx
  forten/src/pages/signup/main/index.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
  forten/src/pagesNew/teacher/index.tsx
  forten/src/pagesNew/teacher/styles.tsx
Labels: Design, Feature, Fix

#123 design: v3 컨설턴트 성적 등록 페이지 퍼블리싱
  forten/src/assets/backgroundImg.png
  forten/src/components/blend/blendEnterGrades.tsx
  forten/src/components/consultant/enterGrades.tsx
  forten/src/pagesNew/consultant/schoolTestGrades.tsx
  forten/src/router.tsx
Labels: Design

#127 124_design: ai 요약 페이지를 퍼블리싱
  forten/src/assets/closeBtn.png
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/modal/rating.tsx
  forten/src/components/modal/schoolGrades.tsx
  forten/src/components/modal/studentAvergy.tsx
  forten/src/components/modal/wordBox.tsx
  forten/src/components/modal/writeButton.tsx
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/src/pages/consultant/AiPrompt/index.tsx
  forten/src/pages/consultant/AiPrompt/styles.tsx
  forten/src/pages/consultant/graderegister/inputTest.tsx
  forten/src/pages/consultant/graderegister/mockTest.tsx
  forten/src/pages/consultant/graderegister/schoolTest.tsx
  forten/src/pages/newpages/Consultant/newModal/consultantrating.tsx
  forten/src/pagesNew/consultant/aiPrompt.tsx
  forten/src/pagesNew/consultant/main.tsx
  forten/src/pagesNew/consultant/schoolTestGrades.tsx
  forten/src/pagesNew/teacher/index.tsx
  forten/src/pagesNew/teacher/styles.tsx
  forten/src/router.tsx
Labels: Design, Feature

#128 126_design/v3 강사평가 리스트 디자인 기능 구현
  forten/src/assets/Boxpencil.svg
  forten/src/assets/MinusLogo.svg
  forten/src/components/consultant/navBar.tsx
  forten/src/components/modal/studentTable.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/main/index.tsx
  forten/src/pages/teacher/main/styles.tsx
Labels: Design, Feature, Fix

#131 129_chore: html2canvas 라이브러리 설치 및 이미지로 저장 기능 추가
  forten/package.json
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/yarn.lock
Labels: Design, Feature

#132 130_Design/ v3 평가등록 모달창 및 모달창 등록페이지 디자인 수정
  forten/src/assets/Xicon.svg
  forten/src/components/modal/rating.tsx
  forten/src/components/teacher/Tmemo.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/newpages/Consultant/newModal/consultantrating.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/main/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
Labels: Design, Feature, Fix

#135 130_ Design/ AI 프롬트, 학생성적페이지 퍼블리싱 완료
  forten/src/assets/BackGround2.jpeg
  forten/src/assets/PDF.svg
  forten/src/assets/sadEmoji.png
  forten/src/assets/sadEmoji.svg
  forten/src/assets/smileEmoji.png
  forten/src/assets/smileEmoji.svg
  forten/src/components/blend/blendEnterGrades.tsx
  forten/src/components/consultant/enterGrades.tsx
  forten/src/components/modal/parentAvergy.tsx
  forten/src/components/modal/writeButton.tsx
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/src/pages/consultant/graderegister/inputTest.tsx
  forten/src/pages/teacher/main/styles.tsx
Labels: Design, Feature, Fix

#136 134_design: 모든 페이지 디자인 수정
  forten/src/components/consultant/grayBox.tsx
  forten/src/components/consultant/greenStatusButton.tsx
  forten/src/components/consultant/navBar.tsx
  forten/src/components/consultant/redStatusButton.tsx
  forten/src/components/consultant/studentInfo.tsx
  forten/src/components/teacher/Tgraybox.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/components/teacher/TstudentInfo.tsx
  forten/src/components/teacher/commentList.tsx
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/consultant/modal/registermodal.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
  forten/src/pages/teacher/evaluationstudent/styles.tsx
  forten/src/pages/teacher/main/styles.tsx
  forten/src/pages/teacher/modal/teacherrating.tsx
Labels: Design, Feature

#138 137_design: 전체 디자인 수정
  forten/src/assets/backImg2.jpg
  forten/src/assets/example.png
  forten/src/components/consultant/navBar.tsx
  forten/src/components/teacher/Tnavbar.tsx
  forten/src/pages/consultant/AiPrompt/aiPrompt.tsx
  forten/src/pages/consultant/consultantmain/index.tsx
  forten/src/pages/consultant/consultantmain/styles.tsx
  forten/src/pages/consultant/graderegister/inputTest.tsx
Labels: Design, Feature

#139 design: 온보딩 두번째, 세번째 페이지 연결
  forten/src/assets/AI.svg
  forten/src/assets/Chart_graph.svg
  forten/src/assets/chart_rating.svg
  forten/src/assets/pdfPic.svg
  forten/src/pages/onboard/thirdpage/index.tsx
  forten/src/pages/onboard/thirdpage/styles.tsx
  forten/src/pages/teacher/evaluationstudent/index.tsx
Labels: Design

#142 141_Dessign_온보딩 첫번째 페이지 및 첫페이지 제작
  forten/package.json
  forten/src/pages/onboard/jaeminpage/index.tsx
  forten/src/pages/onboard/jaeminpage/styles.css
  forten/src/pages/onboard/startpage/index.tsx
  forten/src/pages/onboard/startpage/styles.css
  forten/src/router.tsx
  forten/yarn.lock
Labels: Design
